# Generated by Django 5.0.6 on 2024-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
        migrations.AddField(
            model_name='listing',
            name='imgURL',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
