# Generated by Django 5.0.6 on 2024-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_comments_listing_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imgURL',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
